Wikia/kratos

- x/http_secure_redirect.go
> Fix suffix check

- driver/registry_default.go
- internal/httpclient/README.md
- internal/httpclient/api/openapi.yaml
- internal/httpclient/api_v0alpha1.go
- internal/httpclient/docs/V0alpha1Api.md
- session/handler.go
- session/handler_test.go
- spec/api.json
- spec/swagger.json
Implement session invalidation for identity.
> Implement endpoint for invalidating all sessions for a given identity

- selfservice/strategy/oidc/provider_facebook.go
> PLATFORM-6245 Try to make facebook oidc work

- selfservice/hook/web_hook.go
Avoid connection leaks when using web hooks.
> Blocking hooks improvement

- hash/hash_comparator.go
- quickstart.yml
- selfservice/strategy/password/login.go
https://wikia-inc.atlassian.net/browse/PLATFORM-6129
> PLATFORM-6129 fandom-auth: support legacy hashing algorithm

- driver/registry_default_registration.go
- selfservice/flow/registration/hook_test.go
https://fandom.atlassian.net/browse/PLATFORM-6406
We could revert this change after webhooks are fixed
> PLATFORM-6406 hooks: avoid firing post registration hooks multiple times

- credentials/handler.go
- driver/registry_default.go
- identity/identity.go
* #29 
* https://github.com/ory/kratos/issues/605
the changes.
works.
> Admin endpoint to add, update and remove credentials

- driver/config/.schema/config.schema.json
- selfservice/hook/web_hook.go
https://fandom.atlassian.net/browse/PLATFORM-6471
> PLATFORM-6471  linking/unlinking in Fandom Auth results in linking/unlinking in external-auth

- selfservice/hook/web_hook.go
Improve logs for webhooks so we can debug problems more easily.
> Add more logs to webhook to ease debugging

- persistence/sql/migrations/sql/20210817181232000007_unique_credentials.mysql.up.sql
- persistence/sql/persister_identity.go
> Platform 6436 some migration issues

- identity/handler.go
- internal/httpclient/README.md
- internal/httpclient/api/openapi.yaml
- internal/httpclient/api_default.go
- internal/httpclient/api_v0alpha2.go
- internal/httpclient/docs/DefaultApi.md
- internal/httpclient/docs/V0alpha2Api.md
- selfservice/hook/address_verifier_test.go
- selfservice/strategy/password/strategy.go
- selfservice/strategy/password/validator.go
- spec/api.json
- spec/swagger.json
https://fandom.atlassian.net/browse/PLATFORM-6671
the changes.
works.
> PLATFORM-6671 fandom-auth: allow to validate traits

- go.mod
- go.sum
> PLATFORM-6611 Use `x` fork with `set-cookie` redacted

- cmd/cleanup/background.go
- cmd/cleanup/root.go
- cmd/cleanup/sql.go
- cmd/cliclient/cleanup.go
- cmd/daemon/serve.go
- cmd/root.go
- cmd/serve/root.go
- continuity/persistence.go
- driver/config/config.go
- embedx/config.schema.json
- internal/driver.go
- persistence/reference.go
- persistence/sql/persister.go
- persistence/sql/persister_continuity.go
- persistence/sql/persister_login.go
- persistence/sql/persister_recovery.go
- persistence/sql/persister_registration.go
- persistence/sql/persister_session.go
- persistence/sql/persister_settings.go
- persistence/sql/persister_verification.go
- selfservice/flow/login/persistence.go
- selfservice/flow/recovery/persistence.go
- selfservice/flow/registration/persistence.go
- selfservice/flow/settings/persistence.go
- selfservice/flow/verification/persistence.go
- session/persistence.go
https://github.com/ory/kratos/issues/952
the changes.
works.
> Database cleanup scripts, PLATFORM-6441

- hash/hasher_legacy_fandom.go
- selfservice/hook/web_hook.go
- selfservice/strategy/password/validator.go
> Close body, PLATFORM-6959

- go.mod
- selfservice/strategy/password/validator.go
This should lower memory usage on PROD
> Use ristretto cache for DefaultPasswordValidator

- selfservice/hook/web_hook.go
Enable form fields in PostLogin web hook.
> PLATFORM-7202| add form fields to Login web hook context

- selfservice/strategy/link/strategy_recovery.go
- selfservice/strategy/oidc/strategy_login.go
- selfservice/strategy/oidc/strategy_registration.go
- x/http_secure_redirect.go
https://fandom.atlassian.net/browse/PLATFORM-7349
If this pull request addresses a security. vulnerability, 
I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
> PLATFORM-7349 preserve return_to param between flows

- selfservice/strategy/link/strategy_recovery.go
- selfservice/strategy/oidc/strategy_login.go
- selfservice/strategy/oidc/strategy_registration.go
- x/http_secure_redirect.go
If this pull request addresses a security. vulnerability, 
I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
> PLATFORM- fix oidc redirects on old Kratos version

- .docker/Dockerfile-build
It seems our certs are not needed
> Remove fandom certs

- identity/manager.go
- identity/manager_test.go
- selfservice/strategy/link/strategy_recovery.go
- session/manager_http.go
> PLATFORM-7607 fix recovery flow for 2FA users

- go.mod
- go.sum
> Switch ory/x to local, PLATFORM-6548

- driver/registry_default.go
- driver/registry_default_hooks.go
- embedx/config.schema.json
- selfservice/hook/hooks.go
- selfservice/hook/totp_lookup_secrets_destroyer.go
- selfservice/strategy/lookup/login.go
- selfservice/strategy/lookup/settings.go
- selfservice/strategy/lookup/strategy.go
- selfservice/strategy/lookup/strategy_test.go
Related to https://github.com/Wikia/fandom-frontend/pull/597
the changes.
works.
> PLATFORM-7048 mfa review changes

- go.mod
- go.sum
- internal/registrationhelpers/helpers.go
Pull in https://github.com/Wikia/x/pull/5
> Update ory/x fork reference

- driver/registry_default.go
> fix: set proper maxAge for session cookies

- cmd/daemon/serve.go
- identity/manager.go
Reset email verification flag when email trait was changed.
> PLATFORM-8193| reset email verification flag when identity has email changed

- persistence/sql/persister.go
- persistence/sql/persister_session.go
> fix: additional cleanup of old data, PLATFORM-9042

- .docker/Dockerfile-build
> Fandom master 1 0 0 change dockerfile

- selfservice/hook/web_hook.go
https://fandom.atlassian.net/browse/PLATFORM-9075
> PLATFORM-9075 allow 2 webhook response formats temporarily
